sudo: required
language: node_js
node_js:
 - "8.9.4"
cache:
 directories:
   - "node_modules"
env:
 global:
 - NODE_ENV=test
before_script:
 - psql -c 'create database sendit_test;' -U postgres
 - npm install
script:
 - nyc --reporter=lcov npm run test